### ISSUE TITLE
There is no option to edit the Course name and cost of the course.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#111]
1. Login as as Trainer
2. Create any course
3. Click on Course details and click on Edit icon

Notice that there is no option to edit the course name and price of the course.

**Comment by samurailens** [comment]
please verify and close.

v.2.0.0.

**Comment by NareshTeed** [comment]
![image](https://user-images.githubusercontent.com/37771328/40128456-49d26b2c-594f-11e8-9d52-5b366040eca2.png)
Now we are able to edit the course name and there is no option to edit the Cost of the course.

**Comment by phani434** [comment]
Gangadhar,Can you please look into itNaresh, We will get back to you ASAP ---- On Wed, 16 May 2018 10:53:19 -0500  NareshTeed<notifications@github.com> wrote ---- Now we are able to edit the course name and there is no option to edit the Cost of the course.  —You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by NareshTeed** [comment]
For Courses user is able to edit the course name and cost. For Program user is unable to edit the cost of the program.
