### ISSUE TITLE
With same email id user is able to create multiple accounts (Trainer, Organizer and Student)

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#38]
1. Launch the application -> Click on My Accounts - >Click on Login as a Trainer ->login with gmail id
2. Sign out from Trainer
3. Click on My Accounts - >Click on Organization Admin login->login with gmail id

Issue - Notice that with same gmail id, user is able to login to application.

**Comment by samurailens** [comment]
This is expected behavior. 

Use case : 

1. A normal user joins as 'student'. In this case, he will signup or login from 'my account' page.
2. Now, after a while, this 'student' can also turn as Trainer. In this case, he has to signup again as Trainer in order to mention his skills and specializations. He may very well use the same email account for such transactions. Hence, we cannot void account creation.

The Step #2 can be considered as an organization as well. A student or trainer can GROW as ORGANIZATION. And we need to verify their skills via the separate process, which is the signup process we already implemented for organizations/trainers.
