### ISSUE TITLE
There is no option to edit the existing Assignment details.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#7]
1. Login as Trainer
2. Click on Dashboard
3. Click on My Courses -> Click on Assignment

Notice that there is no edit option for Assignment details.

![image](https://user-images.githubusercontent.com/37771328/37944649-159a52c0-319a-11e8-9426-7dfa147ad2af.png)

**Comment by samurailens** [comment]
Assignments are not supposed to be edited, since there is no user-defined content we are generating. Only document upload is taking place. 

The assignments here are basically documents-based. Trainer or ORganization has to upload document based assignments. Since we don't plan to support document editing, we shall not have edit feature for Assignments.
