### ISSUE TITLE
In 'Language Learning' category, Nursing course is displayed. 

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#90]
1. Login as Organizer/ Trainer
2. Click on Programs
3. Click on Create new program
4. Select category as Language Learning or any other category.
5. Click on Add Courses (make sure you have added different courses under different categories)

Notice that it is showing unrelated courses. Please check the below screenshot:

![image](https://user-images.githubusercontent.com/37771328/39203818-90725418-4813-11e8-9c67-c990e62014b1.png)

**Comment by samurailens** [comment]
Hi Team,

This is an expected behavior.

Collection of courses created by Trainer or Organization. Programmes can have courses from different categories combined.

Example: A Software Course can be combined with Soft Skill like Language and Etiquette and offered as complete JOB TRAINING PROGRAMME.

Let us know further action.
